@LibraryManagementSystem_HostAddress = http://localhost:5059
@id = 1

### Register

POST {{LibraryManagementSystem_HostAddress}}/api/v1/Account/register
Content-Type: application/json

{
  "UserName": "JaneDoe",
  "Email": "jane.doe@example.com",
  "Password": "Pass@word987",
  "ConfirmedPassword": "Pass@word987"
}

### Login

POST {{LibraryManagementSystem_HostAddress}}/api/v1/Account/login
Content-Type: application/json

{
  "Email": "user.admin@example.com",
  "Password": "Pass@word456"
}

### Book

POST {{LibraryManagementSystem_HostAddress}}/api/v1/Book
Content-Type: application/json

{
  "title": "Book Title Test Number 8",
  "synopsis": "A book synopsis for a new test.",
  "authorId": 1,
  "categoryIds": [
    1
  ]
}

###

GET {{LibraryManagementSystem_HostAddress}}/api/v1/Book
Accept: application/json

###

GET {{LibraryManagementSystem_HostAddress}}/api/v1/Book?SortBy=author&IsDescending=false
Accept: application/json

###

GET {{LibraryManagementSystem_HostAddress}}/api/v1/Book/{{id}}
Accept: application/json

###

PUT {{LibraryManagementSystem_HostAddress}}/api/v1/Book/{{id}}
Content-Type: application/json
Accept: application/json

{
  "Title": "Updated Book Title",
  "Synopsis": "Updated book synopsis.",
  "AuthorId": 2,
  "CategoryIds": [
    1,
    2,
    3
  ]
}

###

DELETE {{LibraryManagementSystem_HostAddress}}/api/v1/Book/{{id}}
Accept: application/json

### Member

POST {{LibraryManagementSystem_HostAddress}}/api/v1/Member
Content-Type: application/json

{
  "Name": "Member UserName 2",
  "CardNumber": "0002"
}

###

GET {{LibraryManagementSystem_HostAddress}}/api/v1/Member
Accept: application/json

###

GET {{LibraryManagementSystem_HostAddress}}/api/v1/Member/{{id}}
Accept: application/json

###

PUT {{LibraryManagementSystem_HostAddress}}/api/v1/Member/{{id}}
Content-Type: application/json
Accept: application/json

{
  "Name": "Updated UserName Member",
  "CardNumber": "10001"
}

###

DELETE {{LibraryManagementSystem_HostAddress}}/api/v1/Member/{{id}}
Accept: application/json
