@LibraryManagementSystem_HostAddress = http://localhost:5059

### Register

POST {{LibraryManagementSystem_HostAddress}}/api/v1/Account/register
Content-Type: application/json

{
  "UserName": "JaneDoe",
  "Email": "jane.doe@example.com",
  "Password": "Pass@word987",
  "ConfirmedPassword": "Pass@word987"
}

### Login

POST {{LibraryManagementSystem_HostAddress}}/api/v1/Account/login
Content-Type: application/json

{
  "Email": "john.doe@example.com",
  "Password": "Pass@word123"
}
