services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: Pass@word
      MSSQL_PID: "Developer"
      MSSQL_LOGGING: "verbose"
    ports:
      - "1433:1433"
    volumes:
      - sql-server-data:/var/opt/mssql/
    restart: always

volumes:
  sql-server-data:
    driver: local